### PR TITLE
Astrid - Berlin - Personal GitHub portfolio completed

### PR DESCRIPTION
**Pull request by AstiV**
No struggles so far

### CODE REVIEW

**Comment by Junedoe** [comment]
I guess, just like I did first, you forgot the "Personal GitHub portfolio completed" part ;)

**Comment by AstiV** [comment]
Thanks for pointing this out @Junedoe. So, is the link to this pull request, the link that is to be handed in on the Prework progress page?

**Comment by Junedoe** [comment]
I don't think it would have been really bad if you (or I) forgot the "Personal GitHub portfolio completed" part in the title. But it is probably easier for our teachers to see who finished their exercise :)

**Comment by Junedoe** [comment]
Oh I think I misunderstood you first, sorry. In the email with our assigments it said that we should take a screenshot from the completed status bar from "https://lab.github.com/". I send a link to my screenshot with an online tool -> "https://prnt.sc/" 
(like this: https://prnt.sc/k3zmp2)

**Comment by AstiV** [comment]
Ah, nice! Thanks a lot. From the E-Mail I got it was not so clear to what to do xD
Thanks so much for your explanation!!

**Comment by Junedoe** [comment]
No problem. I just hope I got it right though because if not- we both have it wrong ;D
Will you start in the Berlin course on 30th July as well? Maybe we will be in the same class :)

**Comment by AstiV** [comment]
Haha, well, at least I have something now. Before your explanation I didn't get it at all!!
Yeah, I'm also in the Berlin class starting 30th of July! Nice to meet you, @Junedoe :)

**Pull request closed without merging**
