### PR TITLE
Ruben Aguayo - Barcelona - “Personal GitHub portfolio completed”

### PR DESCRIPTION
**Pull request by rubenaguayo**
Cannot open VSCode from ITerm, so I had to open "index.html" manually from the actual program.

### CODE REVIEW

**Comment by Sami-Az** [comment]
@rubenaguayo I had a similar issue, the 'code' command was not installed for me, so I had to open VSCode, type cmd+shift+p, type : shell command : install 'code' command in PATH

**Comment by rubenaguayo** [comment]
@Sami-Az thank you very much!! It worked the way you mention and helped me a lot!!

**Comment by Sami-Az** [comment]
@rubenaguayo Glad it worked :)

**Comment by jmxxii** [comment]
Just to piggyback off @Sami-Az, you can also open your files in **VScode** by (**⌘ + Right Click**) on the file you want to open.
If you want to open it with a specific editor you have to open your iterm preferences (**⌘+,**), 
1. Go to **Profiles** tab.
2. Create a profile or if you have one already then just select your name.
3. Click the **Advanced** tab within the **Profiles** Tab
4. Under "**Semantic History**" change "**Open with default app**" to "**Open with editor**" 
5. A dropdown list should pop up & select your preferred editor. In this case I assume it's **VScode**.
screen shot 2018-03-20 at 9 11 16 pm

**Pull request closed without merging**
