### PR TITLE
Anghy Pomar, Ironhacker - Miami, Personal GitHub portfolio completed.

### PR DESCRIPTION
**Pull request by apomarn**
Remembering all the syntax.

### CODE REVIEW

**Comment by brennedith** [comment]
Hi @apomarn, the same happens to me, I've found having this file at hand to be useful.

https://education.github.com/git-cheat-sheet-education.pdf

I hope it helps.

**Comment by RFeldman84** [comment]
yes! thank you! I was trying to my own sheet

**Comment by Ashleydarrue** [comment]
I came across the same issue. I find that typing the syntax over and over gets it to stick. I also re-did the activity a few times until it became a habit.

**Comment by RFeldman84** [comment]
Hi this was sent to me I think by accident. This isn’t my lab 

Thank you,
Rachel Feldman

**Pull request closed without merging**
